export const SET_WALLET_AMOUNT_WITHDRAW = "SET_WALLET_AMOUNT_WITHDRAW";
export const SET_WALLET_SELECTED_CURRENCY = "SET_WALLET_SELECTED_CURRENCY";
export const SET_SELECTED_CAMPAIGN_ID = "SET_SELECTED_CAMPAIGN_ID";
